spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect